#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application="$(getApplication)"

# Disable ptrace_scope temporarily for the contiguous memory allocator (CMA)
# echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope

# Improve initial velocity field
runApplication potentialFoam
mv log.potentialFoam log/potentialFoam.log

# Decompose the mesh domain for parallelization
runApplication decomposePar
mv log.decomposePar log/decomposePar.log

# Run the case
runApplication mpiexec -n 100 simpleFoam -parallel
mv log.mpiexec log/mpiexec.log

# Decompose the mesh domain for parallelization
runApplication reconstructPar
mv log.reconstructPar log/reconstructPar.log

# Remove the processor folders
rm -rf processor*/

# Re-enable ptrace_scope
# echo 1 | sudo tee /proc/sys/kernel/yama/ptrace_scope

#------------------------------------------------------------------------------
