#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application="$(getApplication)"

# Create log folders
mkdir -p log

# Generate background mesh
runApplication blockMesh
mv log.blockMesh log/blockMesh.log

# Extract edges from STL for better geometry meshing
runApplication surfaceFeatureExtract
mv log.surfaceFeatureExtract log/surfaceFeatureExtract.log

# Rotate Mesh since created in different coordinate system
transformPoints -rotate-x -90

# Decompose the mesh domain for parallelization of meshing
runApplication decomposePar -constant
mv log.decomposePar log/decomposeParMesh.log

# Parallelization of meshing
runApplication mpirun -n 100 snappyHexMesh -overwrite -parallel 
mv log.mpirun log/mpirunMesh.log

# Reconstruct mesh
runApplication reconstructParMesh -constant
mv log.reconstructParMesh log/reconstructParMesh.log

# Remove the processor folders
rm -rf processor*/

#------------------------------------------------------------------------------
