#!/usr/bin/env bash
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Create log folders
mkdir -p log

# Generate background mesh
runApplication blockMesh
mv log.blockMesh log/blockMesh.log

# Extract edges from STL for better geometry meshing
runApplication surfaceFeatureExtract
mv log.surfaceFeatureExtract log/surfaceFeatureExtract.log

# Rotate Mesh since created in different coordinate system
transformPoints -rotate-x -90

# Decompose the mesh domain for parallelization of simpleFoam
runApplication decomposePar -constant
mv log.decomposePar log/decomposeParMesh.log

# Parallelization of meshing
runApplication mpiexec -n 100 snappyHexMesh -overwrite -parallel
mv log.mpiexec log/mpiexecMesh.log

# Decompose the mesh domain for parallelization
runApplication reconstructParMesh -constant
mv log.reconstructParMesh log/reconstructParMesh.log

# Remove the processor folders
rm -rf processor*/

#Setting turbloc 
runApplication topoSet
mv log.topoSet log/topoSet.log

# Decompose the mesh domain for parallelization of simpleFoam
runApplication decomposePar -constant
mv log.decomposePar log/decomposePar.log

# Run the case
runApplication mpiexec -n 100 simpleFoam -parallel
mv log.mpiexec log/mpiexec.log

# Decompose the mesh domain for parallelization
runApplication reconstructPar -constant
mv log.reconstructPar log/reconstructPar.log

# Remove the processor folders
rm -rf processor*/