#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application="$(getApplication)"

# Create log folders
mkdir -p log

#Make 0 folder
cp -r 0.orig 0

# Generate background mesh
runApplication blockMesh
mv log.blockMesh log/blockMesh.log

# Surface Feature Extract
runApplication surfaceFeatureExtract
mv log.surfaceFeatureExtract log/surfaceFeatureExtract.log

# Decompose the mesh domain for parallelization of meshing
runApplication decomposePar -constant
mv log.decomposePar log/decomposeParMesh.log

# Parallelization of meshing
runApplication mpiexec -n 100 snappyHexMesh -overwrite -parallel 
mv log.mpiexec log/mpiexecMesh.log

# Decompose the mesh domain for parallelization
runApplication reconstructParMesh -constant
mv log.reconstructParMesh log/reconstructParMesh.log

# Remove the processor folders
rm -rf processor*/

# Setting swept area
runApplication topoSet
mv log.topoSet log/topoSet.log

# Decompose the mesh domain for parallelization of meshing
runApplication decomposePar -constant
mv log.decomposePar log/decomposePar.log

# Run the case
runApplication mpiexec -n 100 simpleFoam -parallel
mv log.mpiexec log/mpiexec.log

# Decompose the mesh domain for parallelization
runApplication reconstructPar -constant
mv log.reconstructPar log/reconstructPar.log

# Remove the processor folders
rm -rf processor*/

#------------------------------------------------------------------------------
