#!/usr/bin/env bash
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Create log folders
mkdir -p log

# Setting swept area
runApplication topoSet
mv log.topoSet log/topoSet.log

# Decompose the mesh domain for parallelization of meshing
runApplication decomposePar -constant
mv log.decomposePar log/decomposePar.log

# Run the case
runApplication mpiexec -n 100 pimpleFoam -parallel
mv log.mpiexec log/pimpleFoam.log

# Decompose the mesh domain for parallelization
runApplication reconstructPar
mv log.reconstructPar log/reconstructPar.log

# Remove the processor folders
rm -rf processor*/
