#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#For 1st
cd "Bottom_Ref" 
chmod +x ./Allclean
./Allclean
chmod +x ./Allrun
./Allrun

#For 2nd
cd ..
cd "Mid_Ref" 
chmod +x ./Allclean
./Allclean
chmod +x ./Allrun
./Allrun

#For 3rd
cd ..
cd "Top_Ref" 
chmod +x ./Allclean
./Allclean
chmod +x ./Allrun
./Allrun

#------------------------------------------------------------------------------
